add watering can code
Techwise-Team-15/my_pet pull request #123
Opened 2023-07-29 02:24 UTC by kanan42

2023-07-30 02:19 UTC, Donnyd88 commented
It looks like the elif you added is duplicated. Do we need it twice? Otherwise looks good.

2023-07-30 02:20 UTC, dinaolmelak commented
Wait, which elif? Can you comment on the file next to the line number

2023-07-30 02:23 UTC, dinaolmelak commented
Oh yeah you're right, I see it

2023-07-30 02:27 UTC, dinaolmelak commented on game_util/scene_items.py
> +        elif self.item_id==config.ItemID.watering_can and self.rect.collidepoint(self.interacting_pet.get_location()):
Yeah this elif is duplicated

2023-07-30 15:14 UTC, dinaolmelak requested changes
Just remove one `elif` and do another commit and push to this branch 😃

2023-07-31 23:47 UTC, kanan42 commented on game_util/scene_items.py
> +        elif self.item_id==config.ItemID.watering_can and self.rect.collidepoint(self.interacting_pet.get_location()):
resolved

2023-07-31 23:48 UTC, dinaolmelak approved these changes
LGTM

2023-07-31 23:49 UTC, RuthAnn1 approved these changes
Looks good

2023-08-01 00:28 UTC, merged